// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LayoutDocumentDataSlicesSlice = never;

/**
 * Item in *Layout → Links*
 */
export interface LayoutDocumentDataLinksItem {
  /**
   * Label field in *Layout → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Layout → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Layout → social links*
 */
export interface LayoutDocumentDataSocialLinksItem {
  /**
   * link field in *Layout → social links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * icon field in *Layout → social links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *Layout → awards*
 */
export interface LayoutDocumentDataAwardsItem {
  /**
   * image field in *Layout → awards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.awards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Layout → awards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.awards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Layout → locations*
 */
export interface LayoutDocumentDataLocationsItem {
  /**
   * city field in *Layout → locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.locations[].city
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * top field in *Layout → locations*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.locations[].top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  top: prismic.NumberField;

  /**
   * left field in *Layout → locations*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.locations[].left
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  left: prismic.NumberField;

  /**
   * Address field in *Layout → locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.locations[].address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * share image field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.share_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  share_image: prismic.ImageField<never>;

  /**
   * seo keywords field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.seo_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_keywords: prismic.KeyTextField;

  /**
   * Hero Headline field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.hero_headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_headline: prismic.KeyTextField;

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice> /**
   * Links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  links: prismic.GroupField<Simplify<LayoutDocumentDataLinksItem>> /**
   * privacy policy field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_policy
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  privacy_policy: prismic.LinkField;

  /**
   * terms of use field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.terms_of_use
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  terms_of_use: prismic.LinkField;

  /**
   * social links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_links[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<Simplify<LayoutDocumentDataSocialLinksItem>>;

  /**
   * contact email field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.contact_email
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_email: prismic.KeyTextField;

  /**
   * awards field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.awards[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  awards: prismic.GroupField<Simplify<LayoutDocumentDataAwardsItem>>;

  /**
   * copyright field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copyright
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField /**
   * locations field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.locations[]
   * - **Tab**: Locations
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  locations: prismic.GroupField<Simplify<LayoutDocumentDataLocationsItem>>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | RichTextSliceSlice
  | NewsSlice
  | JoinUsSlice
  | ContactSlice
  | ClientsSlice
  | AreasSlice
  | CaseStudiesSlice
  | TeamSlice
  | SymbolSlice
  | AboutTextSlice
  | TextIntroSlice
  | MapSlice
  | DivisionsSlice
  | NumbersSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * header background field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.header_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_background: prismic.ImageField<never>;

  /**
   * background field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: page.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    "white" | "gradient" | "gradient-dark",
    "filled"
  >;

  /**
   * dark_header field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.dark_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dark_header: prismic.BooleanField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = LayoutDocument | PageDocument;

/**
 * Primary content in *AboutText → Primary*
 */
export interface AboutTextSliceDefaultPrimary {
  /**
   * Title field in *AboutText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image title field in *AboutText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text.primary.image_title
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_title: prismic.ImageField<never>;

  /**
   * theme field in *AboutText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: about_text.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;
}

/**
 * Primary content in *AboutText → Items*
 */
export interface AboutTextSliceDefaultItem {
  /**
   * paragraph field in *AboutText → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for AboutText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTextSliceDefaultPrimary>,
  Simplify<AboutTextSliceDefaultItem>
>;

/**
 * Slice variation for *AboutText*
 */
type AboutTextSliceVariation = AboutTextSliceDefault;

/**
 * AboutText Shared Slice
 *
 * - **API ID**: `about_text`
 * - **Description**: AboutText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTextSlice = prismic.SharedSlice<
  "about_text",
  AboutTextSliceVariation
>;

/**
 * Primary content in *Areas → Primary*
 */
export interface AreasSliceDefaultPrimary {
  /**
   * theme field in *Areas → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: areas.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;

  /**
   * title field in *Areas → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: areas.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Areas → Items*
 */
export interface AreasSliceDefaultItem {
  /**
   * icon field in *Areas → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: areas.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * label field in *Areas → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: areas.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Areas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AreasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AreasSliceDefaultPrimary>,
  Simplify<AreasSliceDefaultItem>
>;

/**
 * Slice variation for *Areas*
 */
type AreasSliceVariation = AreasSliceDefault;

/**
 * Areas Shared Slice
 *
 * - **API ID**: `areas`
 * - **Description**: Areas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AreasSlice = prismic.SharedSlice<"areas", AreasSliceVariation>;

/**
 * Primary content in *CaseStudies → Primary*
 */
export interface CaseStudiesSliceDefaultPrimary {
  /**
   * theme field in *CaseStudies → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: case_studies.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;

  /**
   * title field in *CaseStudies → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *CaseStudies → Items*
 */
export interface CaseStudiesSliceDefaultItem {
  /**
   * title field in *CaseStudies → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *CaseStudies → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for CaseStudies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudiesSliceDefaultPrimary>,
  Simplify<CaseStudiesSliceDefaultItem>
>;

/**
 * Slice variation for *CaseStudies*
 */
type CaseStudiesSliceVariation = CaseStudiesSliceDefault;

/**
 * CaseStudies Shared Slice
 *
 * - **API ID**: `case_studies`
 * - **Description**: CaseStudies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSlice = prismic.SharedSlice<
  "case_studies",
  CaseStudiesSliceVariation
>;

/**
 * Primary content in *Clients → Items*
 */
export interface ClientsSliceDefaultItem {
  /**
   * theme field in *Clients → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: clients.items[].theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;

  /**
   * position field in *Clients → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"left" | "right">;

  /**
   * logo field in *Clients → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * image field in *Clients → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *Clients → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Clients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ClientsSliceDefaultItem>
>;

/**
 * Slice variation for *Clients*
 */
type ClientsSliceVariation = ClientsSliceDefault;

/**
 * Clients Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSlice = prismic.SharedSlice<
  "clients",
  ClientsSliceVariation
>;

/**
 * Primary content in *Contact → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Title field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Divisions → Primary*
 */
export interface DivisionsSliceDefaultPrimary {
  /**
   * Title field in *Divisions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: divisions.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * theme field in *Divisions → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: divisions.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;

  /**
   * Custom background color field in *Divisions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: divisions.primary.custom_background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_background_color: prismic.KeyTextField;
}

/**
 * Primary content in *Divisions → Items*
 */
export interface DivisionsSliceDefaultItem {
  /**
   * image field in *Divisions → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: divisions.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Divisions → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: divisions.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * link label field in *Divisions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: divisions.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * theme field in *Divisions → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: divisions.items[].theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;
}

/**
 * Default variation for Divisions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DivisionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DivisionsSliceDefaultPrimary>,
  Simplify<DivisionsSliceDefaultItem>
>;

/**
 * Slice variation for *Divisions*
 */
type DivisionsSliceVariation = DivisionsSliceDefault;

/**
 * Divisions Shared Slice
 *
 * - **API ID**: `divisions`
 * - **Description**: Divisions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DivisionsSlice = prismic.SharedSlice<
  "divisions",
  DivisionsSliceVariation
>;

/**
 * Primary content in *JoinUs → Primary*
 */
export interface JoinUsSliceDefaultPrimary {
  /**
   * Title field in *JoinUs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *JoinUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * theme field in *JoinUs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: join_us.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;
}

/**
 * Primary content in *JoinUs → Items*
 */
export interface JoinUsSliceDefaultItem {
  /**
   * Position field in *JoinUs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * description field in *JoinUs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * theme field in *JoinUs → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: join_us.items[].theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;

  /**
   * Field (OSINT EXAMPLE) field in *JoinUs → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: join_us.items[].field_osint_example
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  field_osint_example: prismic.BooleanField;

  /**
   * Field (3 AREAS INVESTIGATION IND.) field in *JoinUs → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: join_us.items[].field_investigation_industry
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  field_investigation_industry: prismic.BooleanField;
}

/**
 * Default variation for JoinUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JoinUsSliceDefaultPrimary>,
  Simplify<JoinUsSliceDefaultItem>
>;

/**
 * Slice variation for *JoinUs*
 */
type JoinUsSliceVariation = JoinUsSliceDefault;

/**
 * JoinUs Shared Slice
 *
 * - **API ID**: `join_us`
 * - **Description**: JoinUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinUsSlice = prismic.SharedSlice<"join_us", JoinUsSliceVariation>;

/**
 * Primary content in *Map → Primary*
 */
export interface MapSliceDefaultPrimary {
  /**
   * title field in *Map → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * background field in *Map → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: map.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"none" | "gradient">;
}

/**
 * Default variation for Map Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Map*
 */
type MapSliceVariation = MapSliceDefault;

/**
 * Map Shared Slice
 *
 * - **API ID**: `map`
 * - **Description**: Map
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSlice = prismic.SharedSlice<"map", MapSliceVariation>;

/**
 * Primary content in *News → Primary*
 */
export interface NewsSliceDefaultPrimary {
  /**
   * theme field in *News → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: news.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue">;
}

/**
 * Primary content in *News → Items*
 */
export interface NewsSliceDefaultItem {
  /**
   * Title field in *News → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *News → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *News → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *News → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: news.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * link label field in *News → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Default variation for News Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsSliceDefaultPrimary>,
  Simplify<NewsSliceDefaultItem>
>;

/**
 * Slice variation for *News*
 */
type NewsSliceVariation = NewsSliceDefault;

/**
 * News Shared Slice
 *
 * - **API ID**: `news`
 * - **Description**: News
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSlice = prismic.SharedSlice<"news", NewsSliceVariation>;

/**
 * Primary content in *Numbers → Primary*
 */
export interface NumbersSliceDefaultPrimary {
  /**
   * title field in *Numbers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * theme field in *Numbers → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: numbers.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;
}

/**
 * Primary content in *Numbers → Items*
 */
export interface NumbersSliceDefaultItem {
  /**
   * image field in *Numbers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * number field in *Numbers → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].number
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number: prismic.NumberField;

  /**
   * prefix field in *Numbers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].prefix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prefix: prismic.KeyTextField;

  /**
   * suffix field in *Numbers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].suffix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  suffix: prismic.KeyTextField;

  /**
   * label field in *Numbers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * top label field in *Numbers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].top_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_label: prismic.KeyTextField;

  /**
   * popup image field in *Numbers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.items[].popup_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  popup_image: prismic.ImageField<never>;
}

/**
 * Default variation for Numbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumbersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NumbersSliceDefaultPrimary>,
  Simplify<NumbersSliceDefaultItem>
>;

/**
 * Slice variation for *Numbers*
 */
type NumbersSliceVariation = NumbersSliceDefault;

/**
 * Numbers Shared Slice
 *
 * - **API ID**: `numbers`
 * - **Description**: Numbers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumbersSlice = prismic.SharedSlice<
  "numbers",
  NumbersSliceVariation
>;

/**
 * Primary content in *RichTextSlice → Primary*
 */
export interface RichTextSliceSliceDefaultPrimary {
  /**
   * text field in *RichTextSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_slice.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * theme field in *RichTextSlice → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: rich_text_slice.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;
}

/**
 * Default variation for RichTextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextSlice*
 */
type RichTextSliceSliceVariation = RichTextSliceSliceDefault;

/**
 * RichTextSlice Shared Slice
 *
 * - **API ID**: `rich_text_slice`
 * - **Description**: RichTextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceSlice = prismic.SharedSlice<
  "rich_text_slice",
  RichTextSliceSliceVariation
>;

/**
 * Primary content in *Symbol → Primary*
 */
export interface SymbolSliceDefaultPrimary {
  /**
   * Title field in *Symbol → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: symbol.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Symbol → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: symbol.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *Symbol → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: symbol.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Custom Background Color (Hexa) field in *Symbol → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: symbol.primary.custom_background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_background_color: prismic.KeyTextField;
}

/**
 * Default variation for Symbol Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SymbolSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SymbolSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Symbol*
 */
type SymbolSliceVariation = SymbolSliceDefault;

/**
 * Symbol Shared Slice
 *
 * - **API ID**: `symbol`
 * - **Description**: Symbol
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SymbolSlice = prismic.SharedSlice<"symbol", SymbolSliceVariation>;

/**
 * Primary content in *Team → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * theme field in *Team → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: team.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;

  /**
   * background field in *Team → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: solid
   * - **API ID Path**: team.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"solid" | "none", "filled">;

  /**
   * border bottom field in *Team → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: team.primary.border_bottom
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  border_bottom: prismic.BooleanField;
}

/**
 * Primary content in *Team → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * category field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * name field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * position field in *Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].position
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  position: prismic.RichTextField;

  /**
   * email field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * description field in *Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *TextIntro → Primary*
 */
export interface TextIntroSliceDefaultPrimary {
  /**
   * text field in *TextIntro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_intro.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * link label field in *TextIntro → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_intro.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * link field in *TextIntro → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_intro.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * theme field in *TextIntro → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: orange
   * - **API ID Path**: text_intro.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"orange" | "red" | "blue", "filled">;
}

/**
 * Default variation for TextIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextIntro*
 */
type TextIntroSliceVariation = TextIntroSliceDefault;

/**
 * TextIntro Shared Slice
 *
 * - **API ID**: `text_intro`
 * - **Description**: TextIntro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextIntroSlice = prismic.SharedSlice<
  "text_intro",
  TextIntroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataSlicesSlice,
      LayoutDocumentDataLinksItem,
      LayoutDocumentDataSocialLinksItem,
      LayoutDocumentDataAwardsItem,
      LayoutDocumentDataLocationsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutTextSlice,
      AboutTextSliceDefaultPrimary,
      AboutTextSliceDefaultItem,
      AboutTextSliceVariation,
      AboutTextSliceDefault,
      AreasSlice,
      AreasSliceDefaultPrimary,
      AreasSliceDefaultItem,
      AreasSliceVariation,
      AreasSliceDefault,
      CaseStudiesSlice,
      CaseStudiesSliceDefaultPrimary,
      CaseStudiesSliceDefaultItem,
      CaseStudiesSliceVariation,
      CaseStudiesSliceDefault,
      ClientsSlice,
      ClientsSliceDefaultItem,
      ClientsSliceVariation,
      ClientsSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      DivisionsSlice,
      DivisionsSliceDefaultPrimary,
      DivisionsSliceDefaultItem,
      DivisionsSliceVariation,
      DivisionsSliceDefault,
      JoinUsSlice,
      JoinUsSliceDefaultPrimary,
      JoinUsSliceDefaultItem,
      JoinUsSliceVariation,
      JoinUsSliceDefault,
      MapSlice,
      MapSliceDefaultPrimary,
      MapSliceVariation,
      MapSliceDefault,
      NewsSlice,
      NewsSliceDefaultPrimary,
      NewsSliceDefaultItem,
      NewsSliceVariation,
      NewsSliceDefault,
      NumbersSlice,
      NumbersSliceDefaultPrimary,
      NumbersSliceDefaultItem,
      NumbersSliceVariation,
      NumbersSliceDefault,
      RichTextSliceSlice,
      RichTextSliceSliceDefaultPrimary,
      RichTextSliceSliceVariation,
      RichTextSliceSliceDefault,
      SymbolSlice,
      SymbolSliceDefaultPrimary,
      SymbolSliceVariation,
      SymbolSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimary,
      TeamSliceDefaultItem,
      TeamSliceVariation,
      TeamSliceDefault,
      TextIntroSlice,
      TextIntroSliceDefaultPrimary,
      TextIntroSliceVariation,
      TextIntroSliceDefault,
    };
  }
}
