// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_text: defineAsyncComponent(() => import("./AboutText/index.vue")),
  areas: defineAsyncComponent(() => import("./Areas/index.vue")),
  case_studies: defineAsyncComponent(() => import("./CaseStudies/index.vue")),
  clients: defineAsyncComponent(() => import("./Clients/index.vue")),
  contact: defineAsyncComponent(() => import("./Contact/index.vue")),
  divisions: defineAsyncComponent(() => import("./Divisions/index.vue")),
  join_us: defineAsyncComponent(() => import("./JoinUs/index.vue")),
  map: defineAsyncComponent(() => import("./Map/index.vue")),
  news: defineAsyncComponent(() => import("./News/index.vue")),
  numbers: defineAsyncComponent(() => import("./Numbers/index.vue")),
  rich_text_slice: defineAsyncComponent(
    () => import("./RichTextSlice/index.vue"),
  ),
  symbol: defineAsyncComponent(() => import("./Symbol/index.vue")),
  team: defineAsyncComponent(() => import("./Team/index.vue")),
  testimonial: defineAsyncComponent(() => import("./Testimonial/index.vue")),
  text_intro: defineAsyncComponent(() => import("./TextIntro/index.vue")),
});
